server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: product-service
          uri: lb://PRODUCT-CATALOG-SERVICE
          predicates:
            - Path=/api/products/**

        - id: order-service
          uri: lb://ORDER-MANAGEMENT-SERVICE
          predicates:
            - Path=/api/orders/**

          - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**    

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
